# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson 5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lesson 5



pod 'Alamofire', '~> 4.7'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Firebase/Auth'
pod 'Firebase/Database'
end
